# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- esp32

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo Installing packages
    sudo apt-get update
    sudo apt-get install yosys arachne-pnr fpga-icestorm nextpnr-ice40
    echo Creating base folder
    sudo mkdir /opt/riscv/
    echo Downloading prebuild binaries
    sudo wget -c https://github.com/stnolting/riscv-gcc-prebuilt/releases/download/rv32i-4.0.0/riscv32-unknown-elf.gcc-12.1.0.tar.gz -O - | sudo tar -xzf -C /opt/riscv/
    echo Adding Path
    export PATH=$PATH:/opt/riscv/bin
    echo $PATH
    echo Testing binaries
    riscv32-unknown-elf-gcc -v
  displayName: 'Setup prerequisites'

- script: |
    cd rv32
    make rv32
  displayName: 'Build riscv32 core (make in rv32)'

- script: |
    cd ..
    make
  displayName: 'Build all (make in root)'
