# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- agent-pipeline

variables:
  installToolchain: false
  installMakeIP: false
  bitstreamGenerated: false

pool: 'Linux RISC V'

steps:
- script: |
    echo Creating base folder
    ls -al /opt
  displayName: 'Setup folders'
  
- task: DownloadBuildArtifacts@1
  displayName: 'Download Cross Compiler Toolchain for SH4/ARM'
  condition: eq(variables.installToolchain, true)
  inputs:
    buildType: 'specific'
    project: '4a84c380-a821-47d4-b896-7219ca36222f'
    pipeline: '11'
    buildVersionToDownload: 'latest'
    downloadType: 'single'
    artifactName: 'toolchain'
    downloadPath: '/opt'

- task: DownloadBuildArtifacts@1
  displayName: 'Download MakeIP tool for DC'
  condition: eq(variables.installMakeIP, true)
  inputs:
    buildType: 'specific'
    project: '4a84c380-a821-47d4-b896-7219ca36222f'
    pipeline: '10'
    buildVersionToDownload: 'latest'
    downloadType: 'specific'
    artifactName: 'bin'
    itemPattern: '**'
    downloadPath: '/opt/makeip/'

- script: |
    ls -al /opt/makeip/bin/
    chmod +x /opt/makeip/bin/*
    # chmod +x /opt/toolchain/sh-elf/bin/*
    # chmod +x /opt/toolchain/arm-eabi/bin/*
    # echo Downloading prebuild binaries
    # wget -c https://github.com/stnolting/riscv-gcc-prebuilt/releases/download/rv32i-4.0.0/riscv32-unknown-elf.gcc-12.1.0.tar.gz -O - | sudo tar -xz -C /opt/riscv
    # echo Installing packages
    # sudo apt-get update
    # sudo apt-get install yosys arachne-pnr fpga-icestorm nextpnr-ice40 mkisofs gcc-sh4-linux-gnu
  displayName: 'Setup prerequisites'

- script: |
    echo Adding Path
    export PATH=$PATH:/opt/riscv/bin
    export PATH=$PATH:/opt/makeip/bin
    # export PATH=$PATH:/opt/toolchain/sh-elf/bin
    # export PATH=$PATH:/opt/toolchain/arm-eabi/bin
    # configure environment vars for build tools
    source /opt/toolchains/dc/kos/doc/environ.sh 
    echo Testing binaries
    riscv32-unknown-elf-gcc -v
    echo $PATH
    sh-elf-gcc -v
  displayName: 'Setup paths'

- script: |
    echo Adding Path
    export PATH=$PATH:/opt/riscv/bin
    export PATH=$PATH:/opt/makeip/bin
    # export PATH=$PATH:/opt/toolchain/sh-elf/bin
    # export PATH=$PATH:/opt/toolchain/sh-elf/libexec/gcc/sh-elf/9.3.0
    export PATH=$PATH:/opt/toolchains/dc/arm-eabi/bin
    
    # configure environment vars for build tools
    source /opt/toolchains/dc/kos/doc/environ.sh 
    echo Testing binaries
    riscv32-unknown-elf-gcc -v
    echo $PATH
    sh-elf-gcc -v
    mkdir $(Build.ArtifactStagingDirectory)/tools
    make ci
    
    FILE=fpga/obj/gdrom_hw_emulator.bin
    if [ -f $FILE ]; then
      echo "File $FILE exists."
      echo "##vso[task.setvariable variable=bitstreamGenerated;]true"
    else
      echo "File $FILE does not exist."
      exit 1
    fi
  displayName: 'Build all (make in root)'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
      fpga/GNUmakefile
      fpga/obj/gdrom_hw_emulator.bin
      test/obj/*.GI0
      tools/obj/makegdimg
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true
  condition: eq('${{ variables.bitstreamGenerated }}', true)


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'Artifacts'
    publishLocation: 'Container'
  condition: eq('${{ variables.bitstreamGenerated }}', true)
