# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- esp32

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo Creating base folder
    sudo mkdir /opt/riscv
    sudo mkdir /opt/makeip
    sudo ls -al /opt
    echo Adding Path
    export PATH=$PATH:/opt/riscv/bin
    export PATH=$PATH:/opt/makeip/bin
    echo $PATH
  displayName: 'Setup folders and paths'

- task: DownloadBuildArtifacts@1
  inputs:
    buildType: 'specific'
    project: '4a84c380-a821-47d4-b896-7219ca36222f'
    pipeline: '10'
    buildVersionToDownload: 'latest'
    downloadType: 'specific'
    artifactName: 'bin'
    itemPattern: '**'
    downloadPath: '/opt/makeip/'

- script: |
    sudo ls -al /opt/makeip/bin/
    sudo chmod +x /opt/makeip/bin/makeip
    echo Downloading prebuild binaries
    sudo wget -c https://github.com/stnolting/riscv-gcc-prebuilt/releases/download/rv32i-4.0.0/riscv32-unknown-elf.gcc-12.1.0.tar.gz -O - | sudo tar -xz -C /opt/riscv
    echo Testing binaries
    riscv32-unknown-elf-gcc -v
    echo Installing packages
    sudo apt-get update
    sudo apt-get install yosys arachne-pnr fpga-icestorm nextpnr-ice40 mkisofs
  displayName: 'Setup prerequisites and run make'

- script: |
    echo $PATH
    echo Adding Path
    export PATH=$PATH:/opt/riscv/bin
    export PATH=$PATH:/opt/makeip/bin
    make ci
  displayName: 'Build all (make in root)'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
      fpga/obj/gdrom_hw_emulator.bin
      test/obj/*.GI0
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'Artifacts'
    publishLocation: 'Container'
